package org.pratz.mybatis.model;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.USERNAME
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.PASSWORD
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.ENABLED
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	private Boolean enabled;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.USERNAME
	 * @return  the value of PUBLIC.USERS.USERNAME
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.USERNAME
	 * @param username  the value for PUBLIC.USERS.USERNAME
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.PASSWORD
	 * @return  the value of PUBLIC.USERS.PASSWORD
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.PASSWORD
	 * @param password  the value for PUBLIC.USERS.PASSWORD
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.ENABLED
	 * @return  the value of PUBLIC.USERS.ENABLED
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.ENABLED
	 * @param enabled  the value for PUBLIC.USERS.ENABLED
	 * @mbggenerated  Tue Nov 25 16:23:06 ICT 2014
	 */
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}
}